name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        
    - name: Configure CMake
      run: cmake -B ${{gitea.workspace}}/build -DCMAKE_BUILD_TYPE=Release -Dbackport_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build ${{gitea.workspace}}/build --config Release

    - name: Verify Test Executables
      run: |  
        ls -la ${{gitea.workspace}}/build/tests
      
    - name: Test
      working-directory: ${{gitea.workspace}}/build
      run: |
        ctest -C Release --output-on-failure -V