name: macOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Install LLVM with Homebrew
      run: |
        brew update
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
        
    - name: Configure CMake
      run: |
        export CC=$(brew --prefix llvm)/bin/clang
        export CXX=$(brew --prefix llvm)/bin/clang++
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBACKPORT_FORCE_DISABLE_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure