name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 14
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBACKPORT_FORCE_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Verify Test Executables
      run: |  
        ls -la ${{github.workspace}}/build/tests
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ctest -C Release --output-on-failure -V